# Generated by Django 6.0 on 2026-02-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
